### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by eileenfan** [velazcod/Tinfoil-Facebook#110]
//package name: com.danvelazco.fbwrapper
//version: 1.7.5
//target sdk version: android-18
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.facebook.lite }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
 	at android.app.Activity.startActivityForResult(Activity.java:3390)
 	at android.app.Activity.startActivityForResult(Activity.java:3351)
 	at android.app.Activity.startActivity(Activity.java:3587)
 	at android.app.Activity.startActivity(Activity.java:3555)
 	at com.danvelazco.fbwrapper.activity.BaseFacebookWebViewActivity.openExternalSite(BaseFacebookWebViewActivity.java:639)
 	at com.danvelazco.fbwrapper.webview.FacebookWebViewClient.fireOpenExternalSiteListener(FacebookWebViewClient.java:189)
 	at com.danvelazco.fbwrapper.webview.FacebookWebViewClient.shouldOverrideUrlLoading(FacebookWebViewClient.java:133)
 	at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:261)
 	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:363)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by eileenfan** [comment]
No marketing apps on the current devices, throwing such exception, especially on emulator, better check it.
